name: CI
on:
  push:
  pull_request:

jobs:
  foundry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge install OpenZeppelin/openzeppelin-contracts
          forge install OpenZeppelin/account-abstraction@v0.6
          forge install foundry-rs/forge-std

      - name: Check Foundry version
        run: forge --version

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test -vvv

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.3.4
        with:
          node-version: 20
          fail-on: medium
